name: advent13_flutter_performance

dependencies:
  functional_widget_annotation: 0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  functional_widget: ^0.2.1
  build_runner: 1.1.2

flutter:
  uses-material-design: true
  assets:
    - images/profile.jpg